; Deskbot — XIAO ESP32S3 Sense
; 烧录: ./flash_rom.sh all
;
; WiFi / WS: firmware/deskbot_config.h

[platformio]
src_dir = firmware

[env:deskbot_rom_common]
build_flags =
	-DBOARD_HAS_PSRAM
	-DWEBSOCKETS_MAX_DATA_SIZE=1048576

[env:seeed_xiao_esp32s3]
extends = env:deskbot_rom_common
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions/deskbot_rom_8MB.csv
extra_scripts = pre:scripts/prepare_custom_bootloader.py
build_flags =
	${env:deskbot_rom_common.build_flags}
	-DCONFIG_ESP_CONSOLE_NONE=1
lib_deps =
	links2004/WebSockets@^2.6.1
	adafruit/Adafruit ST7735 and ST7789 Library
	adafruit/Adafruit GFX Library
	adafruit/Adafruit BusIO
	bblanchon/ArduinoJson@^7
	bitbank2/JPEGDEC@^1.8.2
	olikraus/U8g2@^2.35.19
	https://github.com/olikraus/U8g2_for_Adafruit_GFX.git
	madhephaestus/ESP32Servo
