[env:deskbot_bootloader]
platform = espressif32
board = seeed_xiao_esp32s3
; arduino 组件用于锁定 ESP-IDF 4.4 + GCC 8.4 工具链
framework = espidf, arduino
monitor_speed = 115200
platform_packages =
	platformio/framework-espidf @ ~3.40407.0
