#pragma once

#include <stdint.h>

/* 摄像头视觉模式（编译期，由 deskbot.local.env → flash_camera.sh 注入）
 *
 * DESKBOT_CAMERA_UPLOAD_JPEG=1         上传 JPEG 到 /camera，远程做人脸识别
 * DESKBOT_CAMERA_LOCAL_FACE_DETECT=1   本地人脸检测，上传关键点到 /device_pipeline
 * DESKBOT_CAMERA_UPLOAD_FPS            JPEG 采集上传帧率（0=不限速，1–30）
 * DESKBOT_CAMERA_FACE_DETECT_FPS       本地检测上传帧率（0=不限速，1–30）
 */

#ifndef DESKBOT_CAMERA_UPLOAD_JPEG
#define DESKBOT_CAMERA_UPLOAD_JPEG 1
#endif

#ifndef DESKBOT_CAMERA_LOCAL_FACE_DETECT
#define DESKBOT_CAMERA_LOCAL_FACE_DETECT 1
#endif

#ifndef DESKBOT_CAMERA_UPLOAD_FPS
#define DESKBOT_CAMERA_UPLOAD_FPS 10
#endif

#ifndef DESKBOT_CAMERA_FACE_DETECT_FPS
#define DESKBOT_CAMERA_FACE_DETECT_FPS 5
#endif

#ifndef DESKBOT_CAMERA_UPLOAD_INTERVAL_MS
#define DESKBOT_CAMERA_UPLOAD_INTERVAL_MS \
  ((uint32_t)(DESKBOT_CAMERA_UPLOAD_FPS > 0 ? (1000 / DESKBOT_CAMERA_UPLOAD_FPS) : 0))
#endif

#ifndef DESKBOT_CAMERA_FACE_DETECT_INTERVAL_MS
#define DESKBOT_CAMERA_FACE_DETECT_INTERVAL_MS \
  ((uint32_t)(DESKBOT_CAMERA_FACE_DETECT_FPS > 0 ? (1000 / DESKBOT_CAMERA_FACE_DETECT_FPS) : 0))
#endif
